/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "string.h"


void
string_1(char *host,char *message)
{
	CLIENT *clnt;
	char * *result_1;
	

#ifndef	DEBUG
	clnt = clnt_create (host, STRING, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
        char *comp_str = strstr(message,"C00L");//compare if input message contains "C00L"
        if(comp_str!=NULL){
	        result_1 = tst_1(&message, clnt);// tst_1 is the function defined in string_clnt.c
        }else{
                printf("include C00L please\n");   
        } 
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main ()
{
	char *host="127.0.0.1";
        char message[1024]; 
        while(1){
                printf("input message:");
                scanf("%s",message);
                string_1(host, message);   
        }
exit (0);
}
