/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "string.h"

char **
tst_1_svc(char **message, struct svc_req *rqstp)
{
	static char * result;
        printf("message is %s,\n",*message);//receive message from client
        char str[1024];
        strcpy(str,*message);
        FILE *fp;
        int i = 0;
	int count=0;
        //find the amount of digit in the string 
        while(i<=strlen(str)) {
             if (isdigit(str[i])) {
                    count++;
             }
	     i++;
	}
	fp= fopen("secret.out","w");//create a file named secret
        fprintf(fp,"Input message is:%s\n The number of Digits:%d\n",*message,count);
	fclose(fp);
	if (fp == NULL){
	      printf("error!");
	      exit(1);
	}
        result = "received";
	/*
	 * insert server code here
	 */

	return &result;
}
