/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRING_H_RPCGEN
#define _STRING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define STRING 87654321
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define TST 1
extern  char ** tst_1(char **, CLIENT *);
extern  char ** tst_1_svc(char **, struct svc_req *);
extern int string_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TST 1
extern  char ** tst_1();
extern  char ** tst_1_svc();
extern int string_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRING_H_RPCGEN */
